const htmlInvoiceTemplateString = `
<!DOCTYPE html>
<html>
  <body>
    <form>
      <div>
        <h3>Your logo</h3>
      </div>
      <input
        id="invoicegen-my-company-input"
        name="invoicegen-my-company-input"
        type="text"
      /><input
        name="invoicegen-full-name-input"
        id="invoicegen-full-name-input"
        type="text"
      /><input
        id="invoicegen-my-company-website-input"
        name="invoicegen-my-company-website-input"
        type="text"
      /><input
        name="invoicegen-my-company-address-input"
        id="invoicegen-my-company-address-input"
        type="text"
      /><input
        name="invoicegen-city-state-zip-input"
        id="invoicegen-city-state-zip-input"
        type="text"
      /><input
        name="invoicegen-country-input"
        id="invoicegen-country-input"
        type="text"
      /><input
        name="invoicegen-phone-input"
        id="invoicegen-phone-input"
        type="phone"
      /><input
        name="invoicegen-email-input"
        id="invoicegen-email-input"
        type="email"
      /><input
        name="invoicegen-client-company-input"
        id="invoicegen-client-company-input"
        type="text"
      /><input
        name="invoicegen-client-address-input"
        id="invoicegen-client-address-input"
        type="text"
      /><input
        name="invoicegen-client-city-state-zip-input"
        id="invoicegen-client-city-state-zip-input"
        type="text"
      /><input
        name="invoicegen-invoice-number-input"
        id="invoicegen-invoice-number-input"
        type="number"
      /><input
        name="invoicegen-invoice-date-input"
        id="invoicegen-invoice-date-input"
        type="date"
      /><input
        name="invoicegen-invoice-due-date-input"
        id="invoicegen-invoice-due-date-input"
        type="date"
      /><input
        id="invoicegen-client-country-input"
        name="invoicegen-client-country-input"
        type="text"
      />
      <table id="invoicegen-table">
        <thead id="invoicegen-table-header">
          <tr>
            <th id="invoicegen-table-header-0"></th>
            <th id="invoicegen-table-header-1"></th>
            <th id="invoicegen-table-header-2"></th>
            <th id="invoicegen-table-header-3"></th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>
      <div>
        <h3>Comments</h3>
        <textarea
          name="invoicegen-notes-input"
          id="invoicegen-notes-input"
          type="text"
        ></textarea>
      </div>
      <div>
        <input
          id="invoicegen-subtotal-label-input"
          name="invoicegen-subtotal-label-input"
          type="text"
        /><input
          name="invoicegen-subtotal-value-input"
          id="invoicegen-subtotal-value-input"
          type="text"
        />
      </div>
      <div>
        <input
          id="invoicegen-tax-label-input"
          name="invoicegen-tax-label-input"
          type="text"
        /><input
          id="invoicegen-tax-value-input"
          name="invoicegen-tax-value-input"
          type="text"
        />
      </div>
      <div>
        <input
          id="invoicegen-discount-label-input"
          name="invoicegen-discount-label-input"
          type="text"
        /><input
          id="invoicegen-discount-value-input"
          name="invoicegen-discount-value-input"
          type="text"
        />
      </div>
      <hr />
      <div>
        <input
          id="invoicegen-total-label-input"
          name="invoicegen-total-label-input"
          type="text"
        /><input
          id="invoicegen-total-value-input"
          name="invoicegen-total-value-input"
          type="text"
        />
      </div>
    </form>
  </body>
</html>

`;
export default htmlInvoiceTemplateString;
